### ISSUE TITLE
Error while defining model

### ISSUE THREAD

**Issue by Anuj040** [huseinzol05/malaya-speech#10]
Hey

I have been trying to use this repo to define a stt model as described [here](https://malaya-speech.readthedocs.io/en/latest/load-stt-transducer-model.html#)
`model = malaya_speech.stt.deep_transducer(model = 'conformer')`

But it throws an error 
```sh
Traceback (most recent call last):
  File "malay_stt/test.py", line 10, in <module>
    model = malaya_speech.stt.deep_transducer(model = 'conformer')
  File "/Users/anuj/Desktop/Work/projects_2021/toy8/malay_stt/.venv/lib/python3.6/site-packages/herpetologist/__init__.py", line 100, in check
    return func(*args, **kwargs)
  File "/Users/anuj/Desktop/Work/projects_2021/toy8/malay_stt/.venv/lib/python3.6/site-packages/malaya_speech/stt.py", line 329, in deep_transducer
    **kwargs
  File "/Users/anuj/Desktop/Work/projects_2021/toy8/malay_stt/.venv/lib/python3.6/site-packages/malaya_speech/supervised/stt.py", line 31, in transducer_load
    stack = 'stack' == splitted[-2]
IndexError: list index out of range
```
It works fine with version _1.1.3_, only encounter this issue in *1.2*
Thanks a lot for your assistance.

**Comment by huseinzol05** [comment]
Will try to solve asap

**Comment by huseinzol05** [comment]
bumped to 1.2.0.1, tested on google colab, https://colab.research.google.com/drive/1TK_N2kqjLgq317DvvpHuRxdiHGoFFYDN?usp=sharing
